#440 Presentation


```{r}
dat<-read.csv("results.csv")
```


Let's take a look at the data.
```{r}
str(dat)
```

Subject should be a factor variable. Additionally, I prefer
it when "pre" precedes "post". So I'm going to refactor those
variables.
```{r}
dat$participant<-factor(dat$participant)
```
Lets create a couple new variables.  
```{r}
dat$wps1<-dat$words1/120
dat$wps2<-dat$words2/dat$time
```


```{r}
library("dplyr")
temp<-dat%>%group_by(group)%>%summarize(means=mean(time),
              sems=sd(time)/sqrt(length(time)))
library("ggplot2")
f<-ggplot(temp,aes(x=factor(group),y=means))+
    geom_bar(stat="identity", color="black")+
    geom_errorbar(aes(ymax=means+sems, ymin=means-sems), width=.1)+

    ggtitle("Motivation by Time in Seconds")+
    labs(x="Group", y="Motivation\n(higher=more motivation")+
    scale_x_discrete(breaks=c("Control","GPCEF","PPCEF"),labels=c("Control","General","Personalized"))+
    theme(plot.title=element_text(size=15,face="bold",vjust=.5))+
    theme(axis.title.x=element_text(size=12,face="bold",vjust=-.25))+
    theme(axis.title.y=element_text(size=12,face="bold",vjust=1))+
    theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
    theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
    coord_cartesian(ylim=c(min(temp$means)-2*max(temp$sems),max(temp$means)+2*max(temp$sems)))+
    theme(panel.border=element_blank(), axis.line=element_line())+
    theme(panel.grid.major.x=element_blank())+
    theme(panel.grid.major.y=element_line(color="darkgrey"))+
    theme(panel.grid.minor.y=element_blank())
f
```

Lets try a 2-way between-subjects ANOVA.

```{r}
 summary(aov(time~group,data=dat))
 summary(aov(words2~group,data=dat)) 
 summary(aov(wps2~group,data=dat))
```


***Fin***